language: android
jdk: oraclejdk8

#sudo: false

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-29.0.2

    # The SDK version used to compile your project
    - android-29

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    - sys-img-armeabi-v7a-android-22
    - sys-img-armeabi-v7a-android-17


install: skip

#script: skip
     


matrix:
  include:
    - sudo: false
      dist: precise
      env: DIST=precise STACK=EC2

notifications:
  email: false
